#!/usr/bin/env bash
#
# Run all dotfiles installers.

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
if [ "$(uname -s)" == "Darwin" ]; then
    echo "› brew bundle"
    brew bundle
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do bash -c "${installer}" ; done

# Run the bootstrap script
script/bootstrap

